name: Build and deploy Functions (Python)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: dsdsdwufunc0     # <-- твой Function App
  AZURE_FUNCTIONAPP_PACKAGE_PATH: src           # код функций лежит в /src
  PYTHON_VERSION: "3.11"                        # у тебя в Deployment Center 3.11

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # requirements.txt лежит в корне репо, поэтому ../requirements.txt
      - name: Install dependencies into .python_packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ../requirements.txt --target ".python_packages/lib/site-packages"

      - name: Create deployment package
        run: |
          zip -r ../package.zip . \
            -x "local.settings.json" ".venv/*" "__pycache__/*" "*.pyc"

      - name: Deploy to Azure Functions
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: package.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_* }}
